#!/usr/bin/env bash

logfile=$PWD/buycraft.log
pidfile=$PWD/buycraft.pid

start() {
    if [ ! -d "node_modules" ]; then
        echo "Please run './install.sh' first"
        exit 1
    fi
    if [ "$pid" == "" ]; then
        echo "Starting buycraft"
        touch $pidfile
        touch $logfile

        forever start --pidFile $pidfile -a -l $logfile -d $PWD/index.js > /dev/null
        echo "Buycraft started"
    else
        echo -e "\nBuycraft is already running\n"                
    fi
}

stop() {
    echo "Shutting down buycraft"
    if [ "$pid" != "" ]; then
        forever stop $pid > /dev/null
        echo "Buycraft shut down"
    else
        echo -e "\nBuycraft is not running";
    fi
}

if [ -f $pidfile ]; then
      read pid < $pidfile
else
      pid=""
fi

case "$1" in            
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    logs)
        tail -f $logfile
        ;;
    *)
        echo "Usage: {start|stop|restart|logs}"
        exit 1
        ;;
esac 
exit 0
